# Docker Compose configuration for NGINX HTTP/3 Gateway
version: '3.8'

services:
  # NGINX HTTP/3 Gateway
  nginx-gateway:
    image: nginx:1.25-alpine
    container_name: linkwithmentor-nginx-gateway
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3 QUIC
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - linkwithmentor-network
    depends_on:
      - user-management
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

  # Rust Gateway Service (alternative to NGINX)
  rust-gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: linkwithmentor-rust-gateway
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_HOST=0.0.0.0
      - GATEWAY_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=dev-secret-key-change-in-production-12345
      - USER_MANAGEMENT_URL=http://user-management:8000
      - CHAT_SERVICE_URL=http://chat:8000
      - VIDEO_SERVICE_URL=http://video:8000
      - MEETINGS_SERVICE_URL=http://meetings:8000
      - PAYMENT_SERVICE_URL=http://payment:8000
      - SAFETY_SERVICE_URL=http://safety:8000
      - RUST_LOG=debug
    depends_on:
      redis:
        condition: service_healthy
      user-management:
        condition: service_started
    networks:
      - linkwithmentor-network
    profiles:
      - rust-gateway
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nginx_logs:
    driver: local

networks:
  linkwithmentor-network:
    external: true